apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tika
  namespace: {{.namespace}}
  labels:
    app: tika
spec:
  replicas: 3
  template:
    metadata:
      labels:
        component: tika
    spec:
      containers:
      - name: tika
        securityContext:
          privileged: false
        image: {{.tikaimage}}
        resources:
          requests:
            memory: "{{.requestmemory}}"
          limits:
            memory: "{{.limitmemory}}"
        imagePullPolicy: Always
        env:
          - name: JAVA_OPTS
            value: "-Xms1Gi -Xmx1Gi"
        ports:
        - containerPort: 9998
          name: transport
          protocol: TCP
