apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/load-balancer-type: Internal
  name: tika
  labels:
    app: tika
spec:
  type: NodePort
  selector:
    app: tika
  ports:
    - name: tika-port
      port: 9998
